name: Beaker Image Builder
description: The Beaker Image Builder builds Docker images and creates Beaker images.
inputs:
  beaker_token:
    description: Beaker user token. This should be stored as a repository secret.
    required: true
  beaker_workspace:
    description: Workspace for the built image. If omitted, the default workspace will be used.
    required: false
  beaker_image_name:
    description: Name for the image. If omitted, the image will named with the repository and commit SHA e.g. repo-abc1234.
    required: false
  beaker_image_name_overwrite:
    description: If set, the image builder will clear the name of any existing image with the desired image name.
    required: false
  dockerfile:
    description: Path to the Dockerfile.
    required: false
    default: 'Dockerfile'
  dockerfile_template:
    description: Use a Dockerfile template instead of a Dockerfile included in the repository.
    required: false
  github_token:
    description: The GitHub token is used to authenticate with the GitHub Package Registry for caching Docker builds. If omitted, caching will be disabled.
    required: false
  spec_file:
    description: The path to the experiment Spec to run when build is complete. 
    required: false
outputs:
  image_id:
    description: Beaker image ID.
runs:
  using: docker
  image: Dockerfile
