name: Beaker Image Builder
description: The Beaker Image Builder builds Docker images and creates Beaker images.
inputs:
  beaker_token:
    description: Beaker user token. This should be stored as a repository secret.
    required: true
  beaker_workspace:
    description: Workspace for the built image. If omitted, the default workspace will be used.
    required: false
  beaker_image_name:
    description: Name for the image. If omitted, the image will named with the repository and commit SHA e.g. repo-abc1234.
    required: false
  dockerfile:
    description: URL To Docker Image.
    required: true
    default: 'Dockerfile'
  github_token:
    description: The GitHub token is used to authenticate with the GitHub Package Registry for caching Docker builds. If omitted, caching will be disabled.
    required: false
outputs:
  image_id:
    description: Beaker image ID.
runs:
  using: docker
  image: Dockerfile
